#release configuration
#Thu Feb 26 13:24:29 PST 2026
projectVersionPolicyId=default
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.org.troop600\:ScoutSight.tag=HEAD
project.scm.org.troop600\:ScoutSight.connection=scm\:git\:https\://github.com/bhotchkies/ScoutSight/
pinExternals=false
completedPhase=check-poms
scm.url=scm\:git\:https\://github.com/bhotchkies/ScoutSight/
scm.developmentCommitComment=@{prefix} prepare for next development iteration
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.scm.org.troop600\:ScoutSight.url=https\://github.com/bhotchkies/ScoutSight/
project.scm.org.troop600\:ScoutSight.developerConnection=scm\:git\:https\://github.com/bhotchkies/ScoutSight/
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
