package org.troop600.scoutsight.html;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Loads {@code config/definitions/mb_definitions.json} which is already in the
 * flat lookup format expected by the template:
 * <pre>{"First Aid MB":{"1":"text...","2a":"text..."},...}</pre>
 *
 * <p>The file is generated by {@code scripts/parse_mb_requirements.py} and can
 * be re-run whenever the source HTML files are updated.
 */
class MBDefinitionsLoader {

    static String loadAsJson(Path path) throws IOException {
        if (!ResourceIO.exists(path)) return "{}";
        return ResourceIO.readString(path);
    }
}
